name: 'Netlify Preview Deploy'

on:
  pull_request:
    types: ['opened', 'edited', 'synchronize']

jobs:
  deploy:
    name: 'Preview'
    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: write
      discussions: write
      statuses: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - uses: nelonoel/branch-name@v1.0.1
      - uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          build_command: 'npm run preview:generate'
          build_directory: 'preview'
          deploy_alias: ${{ env.BRANCH_NAME }}

    # Creates a status check with link to preview
      - name: Status check
        uses: Sibz/github-status-action@v1.1.1
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: Netlify preview
          state: success
          target_url: ${{ env.NETLIFY_PREVIEW_URL }}
    # Comment on the PR with the link
      - name: Add preview links comment to the PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Your PR preview is at: 
            Examples: ${{ env.NETLIFY_PREVIEW_URL }}/examples
            Docs: ${{ env.NETLIFY_PREVIEW_URL }}/docs
            Coverage: ${{ env.NETLIFY_PREVIEW_URL }}/coverage
            
